// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.anymex.desktop.DesktopExtensionLoader`
class DesktopExtensionLoader extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<DesktopExtensionLoader> $type;

  @jni$_.internal
  DesktopExtensionLoader.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'com/anymex/desktop/DesktopExtensionLoader');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DesktopExtensionLoader?> nullableType =
      $DesktopExtensionLoader$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DesktopExtensionLoader> type =
      $DesktopExtensionLoader$Type$();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Lcom/anymex/desktop/DesktopExtensionLoader;',
  );

  /// from: `static public final com.anymex.desktop.DesktopExtensionLoader INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static DesktopExtensionLoader get INSTANCE =>
      _id_INSTANCE.get(_class, const $DesktopExtensionLoader$Type$());

  static final _id_getLoadedAnimeSources = _class.instanceMethodId(
    r'getLoadedAnimeSources',
    r'()Ljava/util/Map;',
  );

  static final _getLoadedAnimeSources = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.util.Map<java.lang.String, eu.kanade.tachiyomi.animesource.AnimeSource> getLoadedAnimeSources()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString, jni$_.JObject> getLoadedAnimeSources() {
    return _getLoadedAnimeSources(
            reference.pointer, _id_getLoadedAnimeSources as jni$_.JMethodIDPtr)
        .object<jni$_.JMap<jni$_.JString, jni$_.JObject>>(
            const jni$_.$JMap$Type$<jni$_.JString, jni$_.JObject>(
                jni$_.$JString$Type$(), jni$_.$JObject$Type$()));
  }

  static final _id_getLoadedMangaSources = _class.instanceMethodId(
    r'getLoadedMangaSources',
    r'()Ljava/util/Map;',
  );

  static final _getLoadedMangaSources = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.util.Map<java.lang.String, eu.kanade.tachiyomi.source.MangaSource> getLoadedMangaSources()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString, jni$_.JObject> getLoadedMangaSources() {
    return _getLoadedMangaSources(
            reference.pointer, _id_getLoadedMangaSources as jni$_.JMethodIDPtr)
        .object<jni$_.JMap<jni$_.JString, jni$_.JObject>>(
            const jni$_.$JMap$Type$<jni$_.JString, jni$_.JObject>(
                jni$_.$JString$Type$(), jni$_.$JObject$Type$()));
  }

  static final _id_aniyomiGetPreferences = _class.staticMethodId(
    r'aniyomiGetPreferences',
    r'(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;',
  );

  static final _aniyomiGetPreferences = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun aniyomiGetPreferences(sourceId: kotlin.String, isAnime: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString aniyomiGetPreferences(
    jni$_.JString string,
    jni$_.JObject? object,
  ) {
    final _$string = string.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _aniyomiGetPreferences(
            _class.reference.pointer,
            _id_aniyomiGetPreferences as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$object.pointer)
        .object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_aniyomiSavePreference = _class.staticMethodId(
    r'aniyomiSavePreference',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;',
  );

  static final _aniyomiSavePreference = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun aniyomiSavePreference(sourceId: kotlin.String, key: kotlin.String, value: kotlin.Any?, isAnime: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString aniyomiSavePreference(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JObject? object,
    jni$_.JObject? object1,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _aniyomiSavePreference(
            _class.reference.pointer,
            _id_aniyomiSavePreference as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$object.pointer,
            _$object1.pointer)
        .object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_unloadExtension = _class.staticMethodId(
    r'unloadExtension',
    r'(Ljava/lang/String;)V',
  );

  static final _unloadExtension = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun unloadExtension(id: kotlin.String): kotlin.Unit`
  static void unloadExtension(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _unloadExtension(_class.reference.pointer,
            _id_unloadExtension as jni$_.JMethodIDPtr, _$string.pointer)
        .check();
  }

  static final _id_initialize = _class.staticMethodId(
    r'initialize',
    r'()V',
  );

  static final _initialize = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun initialize(): kotlin.Unit`
  static void initialize() {
    _initialize(_class.reference.pointer, _id_initialize as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_loadExtensions = _class.staticMethodId(
    r'loadExtensions',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _loadExtensions = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun loadExtensions(folderPath: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString loadExtensions(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    return _loadExtensions(_class.reference.pointer,
            _id_loadExtensions as jni$_.JMethodIDPtr, _$string.pointer)
        .object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_fetchPopular = _class.staticMethodId(
    r'fetchPopular',
    r'(Ljava/lang/String;ILjava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _fetchPopular = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun fetchPopular(className: kotlin.String, page: kotlin.Int, isAnimeObj: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> fetchPopular(
    jni$_.JString string,
    int i,
    jni$_.JObject? object,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final $r = _fetchPopular(
            _class.reference.pointer,
            _id_fetchPopular as jni$_.JMethodIDPtr,
            _$string.pointer,
            i,
            _$object.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_fetchLatestUpdates = _class.staticMethodId(
    r'fetchLatestUpdates',
    r'(Ljava/lang/String;ILjava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _fetchLatestUpdates = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun fetchLatestUpdates(className: kotlin.String, page: kotlin.Int, isAnimeObj: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> fetchLatestUpdates(
    jni$_.JString string,
    int i,
    jni$_.JObject? object,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final $r = _fetchLatestUpdates(
            _class.reference.pointer,
            _id_fetchLatestUpdates as jni$_.JMethodIDPtr,
            _$string.pointer,
            i,
            _$object.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_search = _class.staticMethodId(
    r'search',
    r'(Ljava/lang/String;Ljava/lang/String;ILjava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _search = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun search(className: kotlin.String, query: kotlin.String, page: kotlin.Int, isAnimeObj: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> search(
    jni$_.JString string,
    jni$_.JString string1,
    int i,
    jni$_.JObject? object,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final $r = _search(
            _class.reference.pointer,
            _id_search as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            i,
            _$object.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_fetchDetails = _class.staticMethodId(
    r'fetchDetails',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _fetchDetails = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun fetchDetails(className: kotlin.String, url: kotlin.String, title: kotlin.String, cover: kotlin.String, isAnimeObj: kotlin.Any?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> fetchDetails(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JObject? object,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final $r = _fetchDetails(
            _class.reference.pointer,
            _id_fetchDetails as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$string3.pointer,
            _$object.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_fetchVideoList = _class.staticMethodId(
    r'fetchVideoList',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _fetchVideoList = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun fetchVideoList(className: kotlin.String, url: kotlin.String, name: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> fetchVideoList(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final $r = _fetchVideoList(
            _class.reference.pointer,
            _id_fetchVideoList as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_fetchPageList = _class.staticMethodId(
    r'fetchPageList',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _fetchPageList = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun fetchPageList(className: kotlin.String, url: kotlin.String, name: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  static core$_.Future<jni$_.JString> fetchPageList(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final $r = _fetchPageList(
            _class.reference.pointer,
            _id_fetchPageList as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }
}

final class $DesktopExtensionLoader$NullableType$
    extends jni$_.JType<DesktopExtensionLoader?> {
  @jni$_.internal
  const $DesktopExtensionLoader$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/anymex/desktop/DesktopExtensionLoader;';

  @jni$_.internal
  @core$_.override
  DesktopExtensionLoader? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : DesktopExtensionLoader.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DesktopExtensionLoader?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DesktopExtensionLoader$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DesktopExtensionLoader$NullableType$) &&
        other is $DesktopExtensionLoader$NullableType$;
  }
}

final class $DesktopExtensionLoader$Type$
    extends jni$_.JType<DesktopExtensionLoader> {
  @jni$_.internal
  const $DesktopExtensionLoader$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/anymex/desktop/DesktopExtensionLoader;';

  @jni$_.internal
  @core$_.override
  DesktopExtensionLoader fromReference(jni$_.JReference reference) =>
      DesktopExtensionLoader.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DesktopExtensionLoader?> get nullableType =>
      const $DesktopExtensionLoader$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DesktopExtensionLoader$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DesktopExtensionLoader$Type$) &&
        other is $DesktopExtensionLoader$Type$;
  }
}
